### ISSUE TITLE
Steal the Stealer

### ISSUE THREAD

**Issue by mordoth94** [Nikifishy/CrealStealerV2#1]
Dont trust this Repo.
He`s stealing yours. :)

**Comment by Nikifishy** [comment]
there is no backdoor inside. wym im stealing yours ?

**Comment by mordoth94** [comment]
I use ur Tool and Just a few Moments after your Bot writing with my Webhook
the resulst in my Discord (Was the testbuild so i let hin scan myself,
forget the Discord bzw.)
But May Discord got hacked. There was spamming your GitHub to all my
Friends and in every Server i was logged in..
Than deleted my Server and try to make Gifts to you...

So please... Just be honest.

Nikifishy ***@***.***> schrieb am Mi., 5. Juni 2024, 20:13:
